name = "decipher"
version = "1.2.1"

description = "A collection of handy gleam/dynamic decoders."
licences = ["MIT"]
repository = { type = "github", user = "hayleigh-dot-dev", repo = "decipher" }
links = [
    { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 3.0.0"
birl = ">= 1.6.1 and < 2.0.0"
stoiridh_version = ">= 0.1.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
